### ISSUE TITLE
Limpiado de cookies

### ISSUE THREAD

**Issue by GoodFaut** [Konata400/McWebPanel#2]
Hola Konata400 : 

Le informo de que su panel de control tiene una pequeña vulnerabilidad porque si ha superado el número de intentos no válidos, eliminando la cookie llamada 'PHPSESSID' puede volver a iniciar sesión.

Gracias. 
                                                             ` De parte de GoodFaut. `

**Comment by Konata400** [comment]
Hola, Mateo

Si conozco que se puede borrar, realmente no lo implemente, ya que la mayoría puede cambiar fácilmente de IP utilizando una VPN y saltarse el bloqueo.

Si sabes alguna forma mejor de bloquearlo podría implementarlo.
