### ISSUE TITLE
Limitar Crear usuarios

### ISSUE THREAD

**Issue by BluewolfYT** [Konata400/McWebPanel#4]
Me gustaría que implementases la opción de que los administradores no puedan crear usuarios.

**Comment by Konata400** [comment]
Hay un pequeño detalle antes de continuar.
¿Un Admin sin permisos de creación de usuarios puede editar usuarios creados por el Superadmin?

**Comment by BluewolfYT** [comment]
Haz que el admin que no pueda crear usuarios, tampoco pueda editar usuarios.
